# Retail Sales Analytics – Data Extraction
---
**Project:** Capstone Data Visualization & Analytics  
**Goal:** Initial extraction and understanding of the Superstore retail sales dataset.

## 1. Import Libraries
We start by importing the necessary libraries for data manipulation and visualization.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

# Setting aesthetic parameters for plotting
sns.set_theme(style="whitegrid")
%matplotlib inline

/Users/kritgarg/.matplotlib is not a writable directory
Matplotlib created a temporary cache directory at /var/folders/44/hf5r20_x4y5bf8kz_wld3rj80000gn/T/matplotlib-19ciyw1x because there was an issue with the default path (/Users/kritgarg/.matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.

## 2. Load Dataset
Reading the raw CSV data. Supports both Google Colab and local execution with robust encoding handling.

In [2]:
raw_file_path = None

# 1. Handle Google Colab Environment
if 'google.colab' in sys.modules:
    print("Detected Google Colab Environment.")
    raw_file_path = '/content/superstore.csv'
    
    if not os.path.exists(raw_file_path):
        print("\n--- FILE NOT FOUND ---")
        print("Please upload the 'superstore.csv' file from your local computer.")
        from google.colab import files
        uploaded = files.upload()
        
        if 'superstore.csv' not in uploaded and len(uploaded) > 0:
            uploaded_filename = list(uploaded.keys())[0]
            os.rename(uploaded_filename, 'superstore.csv')
            print(f"Renamed uploaded file '{uploaded_filename}' to 'superstore.csv'")

# 2. Handle Local Environment
else:
    potential_paths = [
        'data/raw/superstore.csv',
        '../data/raw/superstore.csv',
        '../../data/raw/superstore.csv',
        './superstore.csv',
        '/Users/kritgarg/Desktop/Hopper_Horizon_RetailSalesAnalytics/data/raw/superstore.csv'
    ]
    for path in potential_paths:
        if os.path.exists(path):
            raw_file_path = path
            print(f"Found local file at: {path}")
            break

# 3. Load Data with Encoding Fallback
if raw_file_path and os.path.exists(raw_file_path):
    try:
        # Try default UTF-8 first
        df = pd.read_csv(raw_file_path)
        print("Loaded with UTF-8 encoding.")
    except UnicodeDecodeError:
        try:
            # Try Latin-1 (Common for Superstore datasets)
            df = pd.read_csv(raw_file_path, encoding='ISO-8859-1')
            print("Loaded with ISO-8859-1 encoding.")
        except UnicodeDecodeError:
            # Try Windows-1252 as a final common fallback
            df = pd.read_csv(raw_file_path, encoding='Windows-1252')
            print("Loaded with Windows-1252 encoding.")
    
    print(f"Dataset loaded successfully! Shape: {df.shape}")
    display(df.head())
else:
    raise FileNotFoundError("Could not locate 'superstore.csv'.")

Found local file at: ../data/raw/superstore.csv
Loaded with ISO-8859-1 encoding.
Dataset loaded successfully! Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## 3. Basic Dataset Inspection
Performing a high-level check of the dataset's structure.

In [3]:
# Shape of the dataset
print(f"Dataset Shape: {df.shape}")

# List of columns
print(f"\nColumns:\n{df.columns.tolist()}")

# Data types
print(f"\nData Types:\n{df.dtypes}")

Dataset Shape: (9994, 21)

Columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [4]:
# Preview data
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

## 4. Data Integrity Checks
Checking for missing values and duplicates.

In [5]:
print(f"Missing values:\n{df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")

Missing values:
0
Duplicate rows: 0

## 5. Summary Statistics
Generating descriptive statistics for numerical columns.

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,9994.0,4997.500000,2885.163629,1.000,2499.25000,4997.5000,7495.750,9994.000
Postal Code,9994.0,55190.379428,32063.693350,1040.000,23223.00000,56430.5000,90008.000,99301.000
Sales,9994.0,229.858001,623.245101,0.444,17.28000,54.4900,209.940,22638.480
Quantity,9994.0,3.789574,2.225110,1.000,2.00000,3.0000,5.000,14.000
Discount,9994.0,0.156203,0.206452,0.000,0.00000,0.2000,0.200,0.800
Profit,9994.0,28.656896,234.260108,-6599.978,1.72875,8.6665,29.364,8399.976

## 6. Categorical Distribution
Exploring key categorical columns.

In [7]:
categorical_cols = ['Category', 'Sub-Category', 'Region', 'Segment']
for col in categorical_cols:
    if col in df.columns:
        print(f"\nUnique {col}: {df[col].nunique()}")

Unique Category: 3

Unique Sub-Category: 17

Unique Region: 4

Unique Segment: 3

## Conclusion
The data has been successfully loaded. We used an encoding fallback to handle non-standard characters in the CSV file.